# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        # Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module 'c:\projects\HCRTools\inst\CIDatabase\appveyor-tool.ps1'

install:
  ps: Bootstrap

#---------------------------------#
#       build configuration       #
#---------------------------------#

# Adapt as necessary starting from here
services:
  - mssql2012sp1

build_script:
  - ps: iex .\inst\CIDatabase\CIBuild_DBCreate.ps1
  - Rscript -e "source('http://bioconductor.org/biocLite.R')" -e "chooseCRANmirror(ind=81)"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    _R_CHECK_FORCE_SUGGESTS_: 1
    R_ARCH: x64

  matrix:
    - R_VERSION: release

#---------------------------------#
#  notifications configuration    #
#---------------------------------#

notifications:
 - provider: Email
   to:
     - healthcatalystslc+appveyor@mailbox.org
   subject: 'r-appveyor build {{status}}'                          # optional
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
