site_name: healthcare.ai
site_url: http://healthcare.ai
repo_url: https://github.com/HealthCatalystSLC/healthcareai-r

theme: readthedocs
site_favicon: favicon.ico
docs_dir: inst/docs

pages:
- Home: index.md
- Getting started:
  - Where do I begin?: getting-started/where-do-i-begin.md
  - FAQ and Contact: getting-started/FAQ-and-contact.md
  - Profiling Your Data: getting-started/profiling-your-data.md
- Model Pre-processing:
  - Feature engineering overview: model-pre-processing/feature-eng-overview.md
  - Longitudinal Imputation: model-pre-processing/longitudinal-imputation.md
  - Seasonality Handling: model-pre-processing/seasonality-handling.md
- Comparing and Deploying Models:
  - Develop and Compare: comparing-and-deploying/compare.md
  - Deploying a Best Model: comparing-and-deploying/deploy.md
- Healthcare Statistics:
  - Find High Variation: healthcare-statistics/find-variation.md
  - Find Trends: healthcare-statistics/trend-analysis.md
  - Calculate Targeted Correlations: healthcare-statistics/find-targeted-correlations.md
  - Calculate All Correlations: healthcare-statistics/find-all-correlations.md
  - Risk-adjusted Comparisons: healthcare-statistics/risk-adjusted-comparisons.md
  
google_analytics: ['UA-85609357-1', 'auto']